# Generated by Django 2.0.3 on 2018-04-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='is_published',
        ),
        migrations.AddField(
            model_name='challenge',
            name='status',
            field=models.CharField(default=1, max_length=20, verbose_name=(('Open', 'Open'), ('Closed', 'Closed'))),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='closing',
            field=models.DateField(verbose_name='Closing date'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='story',
            field=models.TextField(verbose_name='Story'),
        ),
    ]
