# Generated by Django 2.0.3 on 2018-04-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0002_auto_20180429_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=20),
        ),
    ]
