# Generated by Django 2.0.5 on 2018-05-03 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0008_auto_20180503_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='accept',
            name='Challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='requester.Challenge'),
            preserve_default=False,
        ),
    ]
