# Generated by Django 2.0.5 on 2018-05-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0010_auto_20180503_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requester',
            old_name='fullname',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='accept',
            name='accept',
        ),
    ]
