# Generated by Django 2.0.5 on 2018-05-08 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requester', '0011_auto_20180508_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accept',
            name='accepter',
        ),
        migrations.AddField(
            model_name='accept',
            name='accepter',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
