# Generated by Django 2.0.5 on 2018-05-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0013_auto_20180508_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='accept',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
