# Generated by Django 2.0.5 on 2018-05-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0014_accept_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accept',
            name='slug',
        ),
        migrations.AddField(
            model_name='accept',
            name='options',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Decline', 'Decline'), ('Ignore', 'Ignore')], default=1, max_length=20),
        ),
    ]
