# Generated by Django 2.0.5 on 2018-05-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0015_auto_20180510_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.DateField(blank=True, default='0')),
                ('entry_validation', models.DateField(blank=True, default='0')),
                ('scoring', models.DateField(blank=True, default='0')),
                ('faciliated_judging', models.DateField(blank=True, default='0')),
                ('announce_finalists', models.DateField(blank=True, default='0')),
                ('presentation', models.DateField(blank=True, default='0')),
                ('winners_announcement', models.DateField(blank=True, default='0')),
            ],
        ),
    ]
