# Generated by Django 2.0.5 on 2018-05-11 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0016_dates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dates',
            options={'verbose_name': 'date', 'verbose_name_plural': 'dates'},
        ),
        migrations.AddField(
            model_name='dates',
            name='challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='requester.Challenge'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dates',
            name='announce_finalists',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dates',
            name='entry',
            field=models.DateField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dates',
            name='entry_validation',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dates',
            name='faciliated_judging',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dates',
            name='presentation',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dates',
            name='scoring',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dates',
            name='winners_announcement',
            field=models.DateField(blank=True, default=''),
        ),
    ]
