# Generated by Django 2.0 on 2018-05-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0017_auto_20180511_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accept',
            name='accepter',
        ),
        migrations.RemoveField(
            model_name='accept',
            name='challenge',
        ),
        migrations.AddField(
            model_name='comment',
            name='options',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Decline', 'Decline'), ('Ignore', 'Ignore')], default=1, max_length=20),
        ),
        migrations.DeleteModel(
            name='Accept',
        ),
    ]
