# Generated by Django 2.0 on 2018-05-17 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requester', '0018_auto_20180515_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='view_count',
        ),
        migrations.AddField(
            model_name='dates',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='closing',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='options',
            field=models.CharField(blank=True, choices=[('Accept', 'Accept'), ('Decline', 'Decline'), ('Ignore', 'Ignore')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='dates',
            name='announce_finalists',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='entry',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='entry_validation',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='faciliated_judging',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='presentation',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='scoring',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='winners_announcement',
            field=models.DateField(blank=True),
        ),
    ]
