# Generated by Django 2.0 on 2018-05-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0019_auto_20180517_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dates',
            name='author',
        ),
    ]
