# Generated by Django 2.0 on 2018-05-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0021_dates_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dates',
            name='author',
        ),
    ]
